name: REBOUNDx (python)

on: [push, pull_request, repository_dispatch]

jobs:
  build:
    name: Python tests on ${{ matrix.os }} (${{ matrix.python-version }})
    timeout-minutes: 10

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest, macos-11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install numpy matplotlib
      - name: echo
        run: echo ${{ github.event.event_type }}
      - name: Checkout REBOUND version that triggered
        if: github.event.event_type != 'trigger_rebx'
        uses: actions/checkout@v4
        with: 
          repository: hannorein/rebound
          ref: ${{ github.event.client_payload.ref }}
          path: ./rebound
      - name: Default REBOUND install
        if: github.event.event_type != 'trigger_rebx'
        run: pip install rebound
      - name: Trigger REBOUND version intall
        if: github.event.event_type != 'trigger_rebx'
        run: pip install -e ./rebound
      - name: Install REBOUNDx
        run: pip install -e .
      - name: Output package contents
        run: pip show reboundx -vf
      - name: Run unit tests
        run: python -m unittest discover -s reboundx/test/ -v
