name: REBOUNDx (python)

on: [push, pull_request, repository_dispatch]

jobs:
  build:
    name: Python tests on ${{ matrix.os }} (${{ matrix.python-version }})
    timeout-minutes: 10

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest, macos-11]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install numpy matplotlib

  build_rebound:
    - name: Default build
    if: github.event.event_type == "trigger_rebx"
    steps:   
      - name: checkout REBOUND version that triggered
        uses: actions/checkout@v4
        with: 
          repository: hannorein/rebound
          ref: ${{ github.event.client_payload.ref }}
          path: ./rebound
        run: echo yes
        run: pip install -e ./rebound

  build_reboundx:
    - name: Build package
    steps:
      - name: Install REBOUNDx
        run: pip install -e .
      - name: Output package contents
        run: |
          pip show reboundx -vf

  run_unit_tests:
    - name: Running unittests
    steps:
      run: |
        python -m unittest discover -s reboundx/test/ -v
